-- Code generated by nested2object
width = width or 100
height = height or 100
color = color or {1,1,1}
pivot = pivot or {0.5,0.5}
Node2D(self)

function draw(...)
    love.graphics.replaceTransform(transform)
    love.graphics.setColor(color)
    love.graphics.rectangle('fill', -width*pivot[1], -height*pivot[2], width, height)
end

