-- Code generated by nested2object
Node2D(self)

s = s or 100
color = color or {1,1,0}
speed = speed or 50

function draw(...)
    love.graphics.setColor(color)
    love.graphics.rectangle('fill', -s*0.5, -s*0.5, s, s)
end

function update(...)
    local dt = ...
    local angle = deg2rad(speed * dt)
    transform:rotate(angle)
end

EventManager:register(self, "draw")
EventManager:register(self, "update")
