-- Code generated by nested2object
transform = Transform(200, 100)
color = {1,1,0}
speed = 50
s = 100

function draw(...)
    love.graphics.applyTransform(transform)
    love.graphics.setColor(color)
    love.graphics.rectangle('fill', -s*0.5, -s*0.5, s, s)
end

function update(...)
    local dt = ...
    local angle = deg2rad(speed * dt)
    transform:rotate(angle)
end

EventManager:register(self, "draw")
EventManager:register(self, "update")
